"""Add market data models

Revision ID: 8089e10e8636
Revises: 
Create Date: 2025-07-18 12:11:51.850666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8089e10e8636'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='证券代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='证券名称'),
    sa.Column('asset_type', sa.Enum('STOCK', 'BOND', 'FUND', 'ETF', 'FUTURES', 'OPTIONS', 'FOREX', 'COMMODITY', name='assettype'), nullable=False, comment='资产类型'),
    sa.Column('exchange', sa.String(length=20), nullable=False, comment='交易所'),
    sa.Column('currency', sa.String(length=3), nullable=True, comment='货币'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否活跃'),
    sa.Column('industry', sa.String(length=50), nullable=True, comment='行业'),
    sa.Column('sector', sa.String(length=50), nullable=True, comment='板块'),
    sa.Column('market_cap', sa.Float(), nullable=True, comment='市值'),
    sa.Column('pe_ratio', sa.Float(), nullable=True, comment='市盈率'),
    sa.Column('pb_ratio', sa.Float(), nullable=True, comment='市净率'),
    sa.Column('dividend_yield', sa.Float(), nullable=True, comment='股息率'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_id'), 'market_data', ['id'], unique=False)
    op.create_index(op.f('ix_market_data_symbol'), 'market_data', ['symbol'], unique=True)
    op.create_table('market_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='指数代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='指数名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='指数描述'),
    sa.Column('base_date', sa.DateTime(), nullable=True, comment='基期'),
    sa.Column('base_value', sa.Float(), nullable=True, comment='基期值'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否活跃'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_index_code'), 'market_index', ['code'], unique=True)
    op.create_index(op.f('ix_market_index_id'), 'market_index', ['id'], unique=False)
    op.create_table('index_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_index_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False, comment='交易日期'),
    sa.Column('open_value', sa.Float(), nullable=True, comment='开盘指数'),
    sa.Column('high_value', sa.Float(), nullable=True, comment='最高指数'),
    sa.Column('low_value', sa.Float(), nullable=True, comment='最低指数'),
    sa.Column('close_value', sa.Float(), nullable=True, comment='收盘指数'),
    sa.Column('volume', sa.Float(), nullable=True, comment='成交量'),
    sa.Column('turnover', sa.Float(), nullable=True, comment='成交额'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['market_index_id'], ['market_index.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_history_id'), 'index_history', ['id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_data_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False, comment='交易日期'),
    sa.Column('open_price', sa.Float(), nullable=True, comment='开盘价'),
    sa.Column('high_price', sa.Float(), nullable=True, comment='最高价'),
    sa.Column('low_price', sa.Float(), nullable=True, comment='最低价'),
    sa.Column('close_price', sa.Float(), nullable=True, comment='收盘价'),
    sa.Column('adjusted_close', sa.Float(), nullable=True, comment='复权收盘价'),
    sa.Column('volume', sa.Float(), nullable=True, comment='成交量'),
    sa.Column('turnover', sa.Float(), nullable=True, comment='成交额'),
    sa.Column('ma5', sa.Float(), nullable=True, comment='5日均线'),
    sa.Column('ma10', sa.Float(), nullable=True, comment='10日均线'),
    sa.Column('ma20', sa.Float(), nullable=True, comment='20日均线'),
    sa.Column('ma60', sa.Float(), nullable=True, comment='60日均线'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['market_data_id'], ['market_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_id'), 'price_history', ['id'], unique=False)
    op.create_table('risk_assessment_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessment_results_id'), 'risk_assessment_results', ['id'], unique=False)
    op.create_index(op.f('ix_risk_assessment_results_user_id'), 'risk_assessment_results', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessment_results_user_id'), table_name='risk_assessment_results')
    op.drop_index(op.f('ix_risk_assessment_results_id'), table_name='risk_assessment_results')
    op.drop_table('risk_assessment_results')
    op.drop_index(op.f('ix_price_history_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_index_history_id'), table_name='index_history')
    op.drop_table('index_history')
    op.drop_index(op.f('ix_market_index_id'), table_name='market_index')
    op.drop_index(op.f('ix_market_index_code'), table_name='market_index')
    op.drop_table('market_index')
    op.drop_index(op.f('ix_market_data_symbol'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_id'), table_name='market_data')
    op.drop_table('market_data')
    # ### end Alembic commands ###
